In [2]:
import pandas as pd

In [3]:
pd.__version__

'3.0.5'

Datatype of Pandas
DataFrame : 2D Table with rows and columns
Series : 1D array-like , can hold any data type such as integers, strings, floating-point numbers, and Python objects

Creating DataFrame

In [4]:
data = {
    "name" : ["Bob", "Aman", "Charls", "Jhon"],
    "age" : [24,56,15,78]
}
df = pd.DataFrame(data)
df

     name  age
0     Bob   24
1    Aman   56
2  Charls   15
3    Jhon   78

Reading Data From Files
pd.read_csv(file_path, delimiter=','): Reads CSV (Comma Separated Value) file and returns a Pandas DataFrame
file_path: Path to csv file
delimiter: Symbol separating different columns (default=',')

In [8]:
titanic_df = pd.read_csv("train.csv", delimiter=",", header = 0)
titanic_df.shape

(891, 12)

pd.read_json(file_path, orient="records"): Reads Json file and returns a Pandas DataFrame
file_path: Path to csv file
orient: Indication of expected JSON string format

In [10]:
json_df = pd.read_json("users.json")
type(json_df)

pandas.DataFrame

Accessing Data

In [11]:
# Sneak Peek
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
# Reading a column
name = titanic_df["Name"]
# name = titanic_df.Name #<- limited 
print(name)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [13]:
type(name)

pandas.Series

In [14]:
name_age = titanic_df[["Name", "Age"]]
name_age

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [17]:
# Reading Rows
second_row = titanic_df.loc[2]
second_row

PassengerId                         3
Survived                            1
Pclass                              3
Name           Heikkinen, Miss. Laina
Sex                            female
Age                              26.0
SibSp                               0
Parch                               0
Ticket               STON/O2. 3101282
Fare                            7.925
Cabin                             NaN
Embarked                            S
Name: 2, dtype: object

In [18]:
type(second_row)

pandas.Series

Basic Properties

In [19]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [20]:
titanic_df.shape

(891, 12)

In [21]:
titanic_df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [22]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB